# Generated by Django 6.0.6 on 2026-07-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
                "unique_together": {("usuario", "nombre", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("DEBITO", "Débito"),
                            ("CREDITO", "Crédito"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("OTRO", "Otro"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "GASTO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                (
                    "categoria",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "INGRESO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField()),
                ("año", models.IntegerField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-año", "-mes"],
                "unique_together": {("usuario", "mes", "año")},
            },
        ),
    ]
